# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup Node.js for GPR
      uses: actions/setup-node@v3
      with:
        registry-url: 'https://npm.pkg.github.com/'
        scope: '@PhasePortrait'

    - run: npm install
    - run: npm install electron-packager
    - run: npm run pack:all
    - run: npm run gpr
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
